### ISSUE TITLE
client.getTickets produces an error

### ISSUE THREAD

**Issue by bryan-kc** [uservoice/uservoice-nodejs#10]
Hi, 

I was following the documentation to get a feel for the library. 

```var UserVoice = require('uservoice-nodejs');

var client = new UserVoice.Client({
    subdomain: process.env.USERVOICE_SUBDOMAIN,
    apiKey: process.env.USERVOICE_APIKEY,
    apiSecret: process.env.USERVOICE_APISECRET
});

client.getTickets = function () {
    client.get('tickets')
        .then(function (tickets) {
        console.log(tickets)
    })
    .catch(function (error) {
        console.log(error);
    })
};

```

client.getTickets logs the following error when called.

```
web_1       | TypeError: Cannot assign to read only property '0' of string '<?xml version="1.0" encoding="UTF-8"?>
web_1       | <response>
web_1       | <response_data>
## Redacted Data
web_1       |   </tickets>
web_1       | </response>
web_1       | '
web_1       |     at Object.processDateStrings (/usr/src/app/node_modules/uservoice-nodejs/dist/src/dateParser.js:23:27)
web_1       |     at Client.parse (/usr/src/app/node_modules/uservoice-nodejs/dist/src/v1/client.js:117:40)
web_1       |     at Client.resolveConsumerResponse (/usr/src/app/node_modules/uservoice-nodejs/dist/src/v1/client.js:107:22)
web_1       |     at /usr/src/app/node_modules/uservoice-nodejs/dist/src/v1/client.js:49:128
web_1       |     at passBackControl (/usr/src/app/node_modules/oauth/lib/oauth.js:390:11)
web_1       |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/oauth/lib/oauth.js:409:9)
web_1       |     at emitNone (events.js:91:20)
web_1       |     at IncomingMessage.emit (events.js:185:7)
web_1       |     at endReadableNT (_stream_readable.js:974:12)
web_1       |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
web_1       |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

using version 0.0.13

**Comment by bryan-kc** [comment]
Made a typo in the client.get call. 

Should be as shown in the documentation.

```
var client = new UserVoice.Client({
    subdomain: process.env.USERVOICE_SUBDOMAIN,
    apiKey: process.env.USERVOICE_APIKEY,
    apiSecret: process.env.USERVOICE_APISECRET
});

client.getTickets = function () {
    client.get('tickets.json')
        .then(function (tickets) {
        console.log(tickets)
    })
    .catch(function (error) {
        console.log(error);
    })
};
```
