### ISSUE TITLE
 TypeError: oauth.OAuth is not a constructor

### ISSUE THREAD

**Issue by bigfoam** [uservoice/uservoice-nodejs#7]
I got this issue with the new 0.0.12 release:

```
C:\dev\wsb-apps-uservoice\node_modules\uservoice-nodejs\dist\src\v1\oauthProvider.js:7
        return new oauth.OAuth(baseUrl + "oauth/request_token.json", baseUrl + "oauth/access_token.json", apiKey, apiSecret, '1.0A', null, 'HMAC-SHA1');
               ^

TypeError: oauth.OAuth is not a constructor
    at OAuthProvider.getConsumer (C:\Users\xmao\WebstormDev\wsb-apps-uservoice\node_modules\uservoice-nodejs\dist\src\v1\oauthProvider.js:7:16)
    at new Client (C:\Users\xmao\WebstormDev\wsb-apps-uservoice\node_modules\uservoice-nodejs\dist\src\v1\client.js:23:47)
    at module.exports (C:\Users\xmao\WebstormDev\wsb-apps-uservoice\lib\clients\uservoice.js:18:9)
    at EventEmitter.app.after (C:\Users\xmao\WebstormDev\wsb-apps-uservoice\lib\preboots\index.js:26:49)
    at nextInterceptor (C:\Users\xmao\WebstormDev\wsb-apps-uservoice\node_modules\understudy\index.js:93:23)
    at next (C:\Users\xmao\WebstormDev\wsb-apps-uservoice\node_modules\understudy\index.js:101:31)
    at EventEmitter.verify (C:\Users\xmao\WebstormDev\wsb-apps-uservoice\node_modules\slay\lib\preboot\logger.js:30:7)
    at nextInterceptor (C:\Users\xmao\WebstormDev\wsb-apps-uservoice\node_modules\understudy\index.js:93:23)
    at iterate (C:\Users\xmao\WebstormDev\wsb-apps-uservoice\node_modules\understudy\index.js:108:23)
    at afterPerform (C:\Users\xmao\WebstormDev\wsb-apps-uservoice\node_modules\understudy\index.js:138:13)
    at onListen (C:\Users\xmao\WebstormDev\wsb-apps-uservoice\node_modules\broadway\index.js:141:5)
    at onListen (C:\Users\xmao\WebstormDev\wsb-apps-uservoice\node_modules\create-servers\index.js:82:7)
    at Server.listener (C:\Users\xmao\WebstormDev\wsb-apps-uservoice\node_modules\create-servers\index.js:115:40)
    at Server.collector (C:\Users\xmao\WebstormDev\wsb-apps-uservoice\node_modules\connected\index.js:32:16)
    at Server.g (events.js:291:16)
    at emitNone (events.js:86:13)

```

**Comment by lukeautry** [comment]
@bigfoam Whoops, got the wrong package. Should be all set with 0.0.13.

**Comment by bigfoam** [comment]
Thanks! Seems all good now.
